/**
 * Scaffly — Next.js generator
 * Creates a Next.js project using the App Router with sensible defaults.
 */

import path from 'path';
import { writeFile, writeJson, runCommand } from '../utils/index.js';

/**
 * Generates a complete Next.js (App Router) project at the given path.
 *
 * @param {string} projectName - Used as the package name and page title
 * @param {string} projectPath - Absolute path where the project will be created
 */
export async function generate(projectName, projectPath) {
  // ── package.json ───────────────────────────────────────────────────────────
  await writeJson(path.join(projectPath, 'package.json'), {
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
    },
    dependencies: {
      next: '^14.2.5',
      react: '^18.3.1',
      'react-dom': '^18.3.1',
    },
    devDependencies: {},
  });

  // ── next.config.mjs ────────────────────────────────────────────────────────
  await writeFile(
    path.join(projectPath, 'next.config.mjs'),
    `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`
  );

  // ── app/layout.js ─────────────────────────────────────────────────────────
  await writeFile(
    path.join(projectPath, 'app/layout.js'),
    `import './globals.css';

export const metadata = {
  title: '${projectName}',
  description: 'Generated by Scaffly',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
  );

  // ── app/page.js ───────────────────────────────────────────────────────────
  await writeFile(
    path.join(projectPath, 'app/page.js'),
    `export default function Home() {
  return (
    <main className="container">
      <h1>Welcome to ${projectName}</h1>
      <p>Built with Next.js &mdash; scaffolded by Scaffly</p>
    </main>
  );
}
`
  );

  // ── app/globals.css ───────────────────────────────────────────────────────
  await writeFile(
    path.join(projectPath, 'app/globals.css'),
    `*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
    Ubuntu, sans-serif;
  background: #ffffff;
  color: #111111;
  line-height: 1.6;
}

.container {
  max-width: 960px;
  margin: 4rem auto;
  padding: 0 1.5rem;
}

h1 {
  font-size: 2.5rem;
  margin-bottom: 1rem;
}
`
  );

  // ── .env.local ────────────────────────────────────────────────────────────
  await writeFile(
    path.join(projectPath, '.env.local'),
    `# Local environment variables — do NOT commit this file
# EXAMPLE_API_KEY=your_key_here
`
  );

  // ── .gitignore ────────────────────────────────────────────────────────────
  await writeFile(
    path.join(projectPath, '.gitignore'),
    `# Dependencies
node_modules/

# Next.js build output
.next/
out/

# Production
build/
dist/

# Environment variables — never commit secrets
.env
.env.local
.env.*.local

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Vercel
.vercel

# Misc
.DS_Store
*.pem
`
  );

  // ── Install dependencies ──────────────────────────────────────────────────
  await runCommand('npm', ['install'], projectPath);
}
